### Basic Application Settings
### Server Settings
server:
  port: 8888

### Actuator Settings
management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: "always"
    web:
      exposure:
        include: "*"

### Data Source Settings
spring:
  application:
    name: psybot
  profiles:
    active: ${ENV_PROFILE:local}
#  main:
#    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=psybot"
    user: dbuser
    password: dbpwd
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-numbers-for-enums: true
    mapper:
      accept-case-insensitive-enums: false
  #jpa sql logs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres?currentSchema=psybot"
    username: dbuser
    password: dbpwd
open-chat:
  key: "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"

token:
  jwt:
    secret: "minha-secret-super-segura-e-supimpa"
    expiration: 10000