### Basic Application Settings
### Server Settings
server:
  port: 8888

### Actuator Settings
management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: "always"
    web:
      exposure:
        include: "*"

### Data Source Settings
spring:
  application:
    name: psybot
  data:
    redis:
      host: "localhost"
      port: 6379
      ttl: 300000ms
      timeout: 1000ms
  profiles:
    active: ${ENV_PROFILE:local}
#  main:
#    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=psybot"
    user: dbuser
    password: dbpwd
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-numbers-for-enums: true
    mapper:
      accept-case-insensitive-enums: false
  #jpa sql logs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  reactor:
    #show the context propagation for logs (traceId)
    context-propagation: AUTO

  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres?currentSchema=psybot"
    username: dbuser
    password: dbpwd
open-chat:
  key: "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"

#springdoc:
#  packagesToScan: com.psybot.controller
##  pathsToMatch: /v1, /api/balance/**
#  swagger-ui:
#    protocol: "https"
#    path: "/swagger-ui.html"

token:
  jwt:
    secret: "minha-secret-super-segura-e-supimpa"
    expiration: 10000

#
#
#    redis:
#      timeout: 1000ms
#      lettuce:
#        cluster:
#          refresh:
#            adaptive: true